### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [handonghoo/CPP202309#1]
### 없는 파일
- challenge/week2/candy.cpp 
- challenge/week2/temperature.cpp 
- challenge/week2/temperature2.cpp 
- challenge/week7/recommendation_func.cpp 
- practice/week7/recommendation_base.cpp
	- 위 파일 이름이나 위치를 다시 확인하세요. 해당 소스 파일 채점이 수행되지 않습니다.

### 에러 있음. 아래 파일/에러메세지/솔루션을 확인하세요
- ERROR in challenge/week3/menuif
    - Error: expected '}' [line 19]
       -  main 함수를 닫는 중괄호가 없습니다. 추가해주세요. 

### 기능/코드 대비 주석이 부족합니다. 주석을 추가하거나 쪼개세요.
- Insufficient comments in challenge/week3/countChar
    - 추출된 주석:   자 음 에   비 해   모 음 의   개 수 가   적 음 을   활 용 해 서   각 각 의   개 수 를   구 합 니 다 .
- Insufficient comments in challenge/week7/hamming_dist_func 
- Insufficient comments in practice/week7/hamming_dist

**Comment by handonghoo** [comment]
26fd2af00ab39365f571825241290897d019925d
